# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'bluchat' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bluchat
  pod 'syncano-ios'
  pod 'JSQMessagesViewController'
  pod 'IQKeyboardManagerSwift'

end